export const books = [
  {
    id: 1,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    cover_image: "src/assets/bookcover.png",
    price: 10.99,
  },
  {
    id: 2,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    cover_image: "src/assets/bookcover.png",
    price: 10.99,
  },
  {
    id: 3,
    title: "Dune",
    author: "Harper Lee",
    cover_image: "src/assets/bookcover.png",
    price: 10.99,
  },
  {
    id: 4,
    title: "Abroad in Japan",
    author: "Harper Lee",
    cover_image: "src/assets/bookcover.png",
    price: 10.99,
  },
  {
    id: 5,
    title: "Metro",
    author: "Harper Lee",
    cover_image: "src/assets/bookcover.png",
    price: 10.99,
  },
  {
    id: 6,
    title: "The zoo",
    author: "Harper Lee",
    cover_image: "src/assets/bookcover.png",
    price: 10.99,
  },
  {
    id: 7,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    cover_image: "src/assets/bookcover.png",
    price: 10.99,
  },
  {
    id: 8,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    cover_image: "src/assets/bookcover.png",
    price: 10.99,
  },
  {
    id: 9,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    cover_image: "src/assets/bookcover.png",
    price: 10.99,
  },
];
